= Climate Informatics Conference Hackathon 2020
:imagesdir: ./media
:icons: font
:my_name: Dánnell Quesada
:my_email: dannell.quesada@tu-dresden.de
:source-highlighter: pygments
:pygments-linenums-mode: inline

This repository contains the solution of the _*Late Birds*_ team for the 2020 Climate Informatics Data Challenge, ranked 2^nd^ place. We are mailto:{my_email}[{my_name}] and Aris Marcolongo.

== About the challenge

The original documentation of the challenge, original Jupyter Notebook and test dataset is https://competitions.codalab.org/my/datasets/download/791b6fe7-de61-45ae-8890-05270324da19[here]. The goal of the Hackathon was to predict the visible spectrum (RGB) of an image by using the infra-red channels of satellite output, so we can "see" Earth at night.

Check the webpage of the https://ci2020.web.ox.ac.uk[Conference] for more details and info.

== About Late Birds solution

The following is a short description we did about our solution:

[quote, Late Birds]
____
As an image to image model we started from the well-known U-net, adapted it to be compatible with the image dimensions and used 1 - ssim as a custom loss function. The data was preprocessed neglecting images which contained more than 20% of black pixels in the True Color dataset. All data was scaled between 0 and 1 and a sigmoid final activation consistently used. For regularization we used early stopping (90/10 -- train/validation split).The best U-net was selected by trial and errror looking at the validation error and the best models had 6 levels of depths, 32 as channel seed and a filter width of 3 pixels. We used Adam as optimizer with a constant learning_rate of 0.001.
____

For more details check the `latebirds.ipynb` notebook, some explanation is added, or you can get in contact with us.

=== Code

To see the output from our latest solution, with some comments and explanation, open the `latebirds.ipynb` notebook. For the code only, check `latebirds.py`

=== Resulting animation

Just as an example, this is an animation of out latest solution.

video::./media/test_pred_naive-0.9386.mp4[options="autoplay,loop", width=900, height=600]
